# Generated by Django 3.0.4 on 2020-03-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.SlugField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=4, null=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('rate_to_russian_rub', models.DecimalField(decimal_places=4, max_digits=15, null=True)),
            ],
        ),
    ]
